{% set version = "1.2" %}
{% set name = "ppl" %}

package:
  name: ppl
  version: {{ version }}

source:
  url: http://bugseng.com/products/ppl/download/ftp/releases/{{ version }}/ppl-{{ version }}.tar.gz
  sha256: 6bc36dd4a87abc429d8f9c00c53e334e5041a9b0857cfc00dbad6ef14294aac8
  patches:
    - cling.patch
    - binary-prefix.diff

build:
  number: 1006
  skip: true  # [win]
  run_exports:
    # pin exact version of ppl, there has not been a release in many years so
    # we have no idea what the next version is going to look like
    - {{ pin_subpackage("ppl", max_pin="x.x") }}

requirements:
  build:
    - libtool
    - make
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - m4
    - gmp
    - glpk
  run:
    - gmp
    - glpk

test:
  commands:
    - test -f ${PREFIX}/include/ppl.hh
    - test -f ${PREFIX}/lib/libppl.dylib  # [osx]
    - test -f ${PREFIX}/lib/libppl.so     # [linux]
    - ppl-config --ldflags | grep "\-lppl"
    - ppl-config --ldflags | grep -v "exec_prefix"
    - ppl-config --cflags | grep -v "exec_prefix"
    - ppl-config --cxxflags | grep -v "exec_prefix"

about:
  home: http://bugseng.com/products/ppl/
  license: GPL-3.0-or-later
  license_file: {{ SRC_DIR }}/COPYING
  summary: |
    The Parma Polyhedra Library (PPL) provides numerical abstractions
    especially targeted at applications in the field of analysis and
    verification of complex systems.
  doc_url: http://bugseng.com/products/ppl/documentation

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
