travis:
  secure:
    BINSTAR_TOKEN: L1VvsvYBjHu4Pqhx/pvfJyll0iS/49rNlTcR/N3p6zHjYkUiI/vsn5LcQCsyEpgjgIIGFU9YqLyxan0H4LwMLshC7lmH5qtGGQm10oYMKkTUyUfWl6CEvNUVwtY9329s25wRvSLp8fEVnIwze5rhsyJqlGv5X4c7+3mT/vgsN++kjRHlKn+T7cdl0nlqUcAuuf4qiB/jHtajPVsuWCXZHG8Fc0Z8KuIXpwHudHI9DC/8sQ1XbeB0/Ba+ZsRSGSQ3j1gQM0POW3EHx3gQMQZ6qxsLvSOi1eOQhUH+mgSKeRAWGnP/6WWtGVNm8zDLsLcuYjRl7OHb2znWKaqAMqpS3Zp3ZBuroTtQJR/7bL3yA/W0hxsAFkC6ujrjSn8TmVJUNz++PqGA5f7vjQ/n2/lv7cJmeWGa5uh4TtaPpNyLWpyLxZfCqnWOH4IkJzOJN4j0qtUTz9iRDw3oThyBnU4pEaIYmf1WIvqCmwrqiGmlDGgJaB4qMHpJ4dPD90mesZKtSWRcl3yoUZAswpDQWHXkD8gn32jctCIAP/kYaOS9bIrl5CcBIh528Wvv4ppWu4qZuUiR4+LkOLwS+F7yfUpc5ca9RMCeNSpBfA038JiUu2iz2dhw8f0nzRQykx7EgqVTjv5vTnCyBBpRt1ET72jNaCvDQddH00Wv/jvmy9xYo8U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
